import streamlit as st

st.set_page_config(page_title="Incident Reports", page_icon="🚨", layout="wide")

st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #fff7ed 0%, #fdf2f8 35%, #eef2ff 75%, #ecfeff 100%);
    color: #111827;
}
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #ffffff, #f8fafc);
    border-right: 1px solid #e5e7eb;
}
[data-testid="stSidebar"] * {
    color: #334155 !important;
    font-weight: 600;
}
.card {
    padding: 30px;
    border-radius: 26px;
    background: rgba(255,255,255,0.96);
    border: 1px solid #e5e7eb;
    box-shadow: 0 14px 35px rgba(148,163,184,0.16);
}
.alert-card {
    padding: 30px;
    border-radius: 26px;
    background: linear-gradient(135deg, #ffe4e6, #ffffff);
    border: 1px solid #fecdd3;
    box-shadow: 0 14px 35px rgba(244,63,94,0.16);
}
.badge-red {
    background:#fee2e2;
    color:#b91c1c;
    padding:8px 14px;
    border-radius:999px;
    font-weight:800;
}
.badge-yellow {
    background:#fef3c7;
    color:#92400e;
    padding:8px 14px;
    border-radius:999px;
    font-weight:800;
}
</style>
""", unsafe_allow_html=True)

st.title("🚨 Incident Reports")
st.caption("Audit-ready incident record generated by the monitoring agent")

incident = {
    "incident_type": "Model Monitoring Alert",
    "batch_risk_level": "High Risk",
    "decision": "Escalate: Significant feature and prediction drift detected.",
    "summary_metrics": {
        "severe_feature_drift_count": 2,
        "moderate_feature_drift_count": 0,
        "prediction_psi": 0.5454,
        "auc_baseline": 0.7100,
        "auc_drifted": 0.6944,
        "auc_drop": 0.0156
    },
    "top_drift_features": [
        {"feature": "PAY_0", "PSI": 1.9833, "Drift_Level": "Severe Drift"},
        {"feature": "LIMIT_BAL", "PSI": 0.4346, "Drift_Level": "Severe Drift"}
    ],
    "recommended_actions": [
        "Notify model owner + risk team",
        "Run deeper diagnostics",
        "Freeze automated decisioning if high-stakes",
        "Collect additional validation data",
        "Prepare retraining plan"
    ],
    "requires_human_approval": True,
    "human_approval_status": "PENDING"
}

left, right = st.columns([1.2, 1])

with left:
    st.markdown("""
    <div class="alert-card">
        <h3>🚨 Incident: Model Monitoring Alert</h3>
        <p><b>Status:</b> <span class="badge-yellow">Pending Human Approval</span></p>
        <p><b>Risk Level:</b> <span class="badge-red">High Risk</span></p>
        <p><b>Decision:</b> Escalate due to significant feature and prediction drift.</p>
        <p><b>Audit Purpose:</b> This record documents what was detected, why it was escalated, and why human review is required before intervention.</p>
    </div>
    """, unsafe_allow_html=True)

with right:
    st.markdown("""
    <div class="card">
        <h3>📌 Governance Requirement</h3>
        <p>No automated retraining, threshold change, or decision freeze should occur until the incident is reviewed.</p>
        <p><b>Approval Status:</b> Pending</p>
    </div>
    """, unsafe_allow_html=True)

st.markdown("## Structured Audit Log")

with st.expander("View full JSON incident report"):
    st.json(incident)